//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "category_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub category_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::memory_categories::Entity",
        from = "Column::CategoryId",
        to = "super::memory_categories::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MemoryCategories,
    #[sea_orm(
        belongs_to = "super::memory_items::Entity",
        from = "Column::ItemId",
        to = "super::memory_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MemoryItems,
}

impl Related<super::memory_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemoryCategories.def()
    }
}

impl Related<super::memory_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemoryItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
