//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "enrichment_records")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "unique_enrichment")]
    pub user_scope: String,
    #[sea_orm(unique_key = "unique_enrichment")]
    pub memory_id: Uuid,
    #[sea_orm(unique_key = "unique_enrichment")]
    pub engine_kind: String,
    #[sea_orm(unique_key = "unique_enrichment")]
    pub engine_version: String,
    pub enriched_at: DateTimeWithTimeZone,
    pub card_ids: Option<Vec<Uuid>>,
    pub success: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub extra: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::memory_items::Entity",
        from = "Column::MemoryId",
        to = "super::memory_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MemoryItems,
}

impl Related<super::memory_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemoryItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
