//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "memory_categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(
        column_type = "String(StringLen::N(255))",
        unique_key = "unique_category_name"
    )]
    pub user_scope: String,
    #[sea_orm(
        column_type = "String(StringLen::N(255))",
        unique_key = "unique_category_name"
    )]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub embedding: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::category_items::Entity")]
    CategoryItems,
}

impl Related<super::category_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoryItems.def()
    }
}

impl Related<super::memory_items::Entity> for Entity {
    fn to() -> RelationDef {
        super::category_items::Relation::MemoryItems.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::category_items::Relation::MemoryCategories
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
