//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "memory_cards")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub kind: String,
    pub entity: String,
    pub slot: String,
    #[sea_orm(column_type = "Text")]
    pub value: String,
    pub polarity: Option<String>,
    pub event_date: Option<DateTimeWithTimeZone>,
    pub document_date: Option<DateTimeWithTimeZone>,
    pub version_key: Option<String>,
    pub version_relation: String,
    pub source_memory_id: Option<Uuid>,
    pub engine: String,
    pub engine_version: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub confidence: Option<f64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub extra: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::memory_items::Entity",
        from = "Column::SourceMemoryId",
        to = "super::memory_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MemoryItems,
}

impl Related<super::memory_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemoryItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
