//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "memory_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub user_scope: String,
    pub resource_id: Option<Uuid>,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub memory_type: String,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub embedding: Option<Json>,
    pub happened_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub extra: Option<Json>,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub content_hash: String,
    pub reinforcement_count: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
