//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "memory_card_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub memory_card_id: Uuid,
    pub version: i32,
    pub parent_version_id: Option<Uuid>,
    pub version_relation: String,
    pub entity: String,
    pub slot: String,
    #[sea_orm(column_type = "Text")]
    pub value: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::memory_cards::Entity",
        from = "Column::MemoryCardId",
        to = "super::memory_cards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MemoryCards,
}

impl Related<super::memory_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemoryCards.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
