//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "memory_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub user_scope: String,
    pub resource_id: Option<Uuid>,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub memory_type: String,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub embedding: Option<Json>,
    pub happened_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub extra: Option<Json>,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub content_hash: String,
    pub reinforcement_count: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub version: i32,
    pub parent_version_id: Option<Uuid>,
    pub version_relation: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::category_items::Entity")]
    CategoryItems,
    #[sea_orm(has_many = "super::memory_cards::Entity")]
    MemoryCards,
    #[sea_orm(has_many = "super::memory_item_versions::Entity")]
    MemoryItemVersions,
    #[sea_orm(
        belongs_to = "super::resources::Entity",
        from = "Column::ResourceId",
        to = "super::resources::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Resources,
}

impl Related<super::category_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoryItems.def()
    }
}

impl Related<super::memory_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemoryCards.def()
    }
}

impl Related<super::memory_item_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemoryItemVersions.def()
    }
}

impl Related<super::resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Resources.def()
    }
}

impl Related<super::memory_categories::Entity> for Entity {
    fn to() -> RelationDef {
        super::category_items::Relation::MemoryCategories.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::category_items::Relation::MemoryItems.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
