//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "memory_item_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub memory_item_id: Uuid,
    pub version: i32,
    pub parent_version_id: Option<Uuid>,
    pub version_relation: String,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub extra: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::memory_items::Entity",
        from = "Column::MemoryItemId",
        to = "super::memory_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MemoryItems,
}

impl Related<super::memory_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemoryItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
